name: FinanzasApp
options:
  bundleIdPrefix: com.matias.finanzas
  xcodeVersion: "15.4"

settings:
  base:
    PRODUCT_NAME: FinanzasApp
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "-"
    AD_HOC_CODE_SIGNING_ALLOWED: YES
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: "1.0.0"

targets:
  FinanzasApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - App
      - Models
      - Services
      - Views
      - Helpers
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.matias.finanzas.FinanzasApp
        INFOPLIST_KEY_CFBundleDisplayName: "Mis Finanzas"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSAppTransportSecurity_NSAllowsArbitraryLoads: "YES"
        CODE_SIGN_IDENTITY: "-"
        AD_HOC_CODE_SIGNING_ALLOWED: YES
